applications/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView,
)
app_name = 'applications'
urlpatterns = [
    path('register/', register, name="register"),
    path('sign_up/', MySignUpView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password_change/', PasswordChangeView.as_view(success_url='accounts/password_change/done/'), name="password_change"),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', PasswordResetView.as_view(success_url='done/'), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view( success_url='/accounts/reset/done/'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('edit/<int:id>', edit_account, name="edit_account"),

    #TODO
    # path('profile/update', CustomProfileEditView.as_view(), name="update_porfile"),
]

default_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                   path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
                   path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
                   path('admin/', admin.site.urls),
                   path('settings/', include('livesettings.urls')),
                   path('faicon/', include('faicon.urls')),

                   path('accounts/', include('applications.user.urls', namespace="accounts")),

                   path('', include('applications.shop.urls')),

                  path('', include('applications.product.urls.urls')),
               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Default Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/card_product.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet"  href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>



</head>
<body>
{% block header %}
    {% block login %}
    {% endblock %}
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'js/menu.js' %}"></script>
</body>
</html>

templates/header.html
{% include 'registration/login.html' %}
{% block header %}
    <header id="Header">
        <nav class="navbar navbar-expand-md navbar-light fixed-top  sticky-top"
             style="background-color: #e3f2fd;position: fixed!important;">
            {% if logo %}
                {% for l in logo %}
                    <a class="logo-mini logo-lg" href="/"><img src="/media/{{ l.logo }}"></a>
                {% endfor %}
            {% else %}
                <a class="navbar-brand" href="/">Home</a>

            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarCollapse">
                <ul class="navbar-nav mr-auto list-inline mx-auto justify-content-center d-lg-none">
                    {% if departments_all %}
                        {% for department in departments_all %}
                            <li class="nav-item">
                                <a class="nav-link" href={{ department.get_absolute_url }}>{{ department }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <form class="form-inline mt-2 mt-md-0 list-inline mx-auto justify-content-center" method="get"
                      action="{% url "search" %}">{% csrf_token %}
                    <input name="search" class="form-control mr-sm-2 input-lg" type="text" placeholder="Pesquisar"
                           aria-label="Search" size="50">
                    <button class="btn btn-outline-success mr-sm-2 my-2 my-sm-0" type="submit"><i
                            class="fa fa-search"></i></button>
                </form>
                {% if user.is_authenticated %}
                    <div class="dropdown show">
                        <button class="btn btn-secondary dropdown-toggle mr-sm-2" id="dropdownMenuLink"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.first_name }}
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:edit_account' user.id %}">Minha conta</a>
                            <a class="dropdown-item" href="#">Meus pedidos</a>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a>
                        </div>
                    </div>
                {% else %}
                    <button class="btn btn-outline-secondary mr-sm-2" data-toggle="modal"
                            data-target="#elegantModalForm">Logar
                    </button>
                {% endif %}


                <div class="btn-group">
                    <button type="button" class="btn btn-outline-info" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                        <i class="fa fa-shopping-cart"></i>
                        {% if carrinho %}
                            <span class="badge badge-primary badge-pill">{{ carrinho|length }}</span>
                        {% else %}
                            <span class="badge badge-primary badge-pill">0</span>
                        {% endif %}
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if carrinho %}
                            <div class="scrollbar-y">
                                {% for item in carrinho %}
                                    <div class="card">
                                        <div class="card-header">
                                            {{ item.sku.product.name }}
                                        </div>
                                        <div class="card-body">
                                            <img src="/media/{{ item.sku.image.img }}">
                                            <p>{{ item.sku.product.name }} - {{ item.sku.name }}</p>
                                            <label>
                                                <input value="{{ item.quantity }}">
                                            </label>
                                            <p>{{ item.sku.price.price }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="card-footer">
                                <p class="card-text"><small class="text-muted">{{ sum }}</small></p>
                                <a class="btn btn-success" href="{% url 'shopping_cart' %}">Checkout</a>
                            </div>
                        {% else %}
                            <div class="card">
                                <div class="card-header">
                                    Ops
                                </div>
                                <div class="card-body">
                                    <p>Você ainda não adicionou nenhum item ao carrinho</p>
                                </div>

                                <div class="card-footer">
                                    <p class="card-text"><small class="text-muted">total</small></p>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <div class="d-flex justify-content-center border border-info" style="padding-top: 5px">
            <div id="departments" class="d-none d-lg-block ">
                <ul class="navbar-nav mr-auto list-inline mx-auto justify-content-center ">
                    {% if departments_all %}
                        {% for department in departments_all %}
                            <li class="nav-item">
                                <a class="nav-link text text-dark"
                                   href={{ department.get_absolute_url }}>{{ department }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
{% endblock %}
{% block content %}
{% endblock %}

{% block footer %}
    <div class="carousel"></div>
    <footer class="page-footer font-small blue pt-4 text-center color_custom">

        <div class="footer-copyright text-center py-3">
            <div class="container">
                <p>Projeto desenvolvido por &copy; mascDriver! <a
                        href="https://api.whatsapp.com/send?phone=5549985058553" target="_blank">Entre em contato</a>
                </p>
            </div>
        </div>
    </footer>
{% endblock %}

templates/index.html
{% extends 'header.html' %}
{% block content %}
    {% if banners %}
        <div class="">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for banner in banners %}
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for banner in banners %}
                        {% if forloop.last %}
                            <div class="carousel-item active">
                        {% else %}
                            <div class="carousel-item">
                        {% endif %}

                    <img class="first-slide img-fluid" src="/media/{{ banner.banner }}" alt="First slide">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            <h1>{{ banner.name }}</h1>
                            <p>{{ banner.texto }}</p>
                            <p><a class="btn btn-lg btn-primary" href="#" role="button">Veja mais</a></p>
                        </div>
                    </div>
                    </div>
                    {% endfor %}


                    </div>
                    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>

    {% endif %}
    <div class="carousel"></div>

    <div class="container">

        <form  method="POST" class="teste">
            {% csrf_token %}
            <div class="row" >

                {% for produto in produtos %}
                    <input value="{{ produto.id }}" name="produto" hidden>
                    <a href="{{ produto.get_absolute_url }}" class="custom-card">
                        <div class="col-md-4 col-xs-12">
                            <div class="container_product ">
                                <div class="card_product" >
                                    <div class="imgBx" >
                                        <img type="png" class="img-responsive" src="/media/{{ produto.image.img }}" alt="{{ produto.image }}" >
                                    </div>
                                    <div class="contentBx  form-control">
                                        <p class="font-weight-bold">{{ produto }}</p >
                                        <p class="font-weight-bold">{{ produto.price.price }} R$</p>
                                        <button type="submit" class=" btn btn-outline-success teste ">Adicionar ao carrinho</button>
                                        <br>
                                        <a class="font-weight-bold btn" href="#">Mais delalhes</a >
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </form>

    </div>

    <script>
        $(document).ready(function () {
            $(".teste").submit(function (e) {
                // preventing from page reload and default actions
                e.preventDefault();
                // serialize the data for sending the form data.
                var serializedData = $(this).serialize();
                // make POST ajax call
                $.ajax({
                    type: 'POST',
                    url: "{% url 'add_to_cart' %}",
                    data: serializedData,
                    success: function () {
                        $('#message').html("<h2>Contact Form Submitted!</h2>")
                    }
                });
                return false; //<---- move it here
            });

        });
    </script>
{% endblock %}

templates/product_render.html
{% extends 'header.html' %}
{% block content %}
    <div class="carousel"></div>
    <main class="text-center">
        <div class="row">
            <div class=" col-md-2 col-xs-12">
                <div class="list-group">
                    <li class="list-group-item list-group-item-dark">Departamentos</li>
                    {% for dep in departments %}
                        <a href="{{ dep.get_absolute_url }}" class="list-group-item list-group-item-action">{{ dep }}</a>
                    {% endfor %}
                    <br>
                    <li class="list-group-item list-group-item-dark">Categorias</li>

                    {% for category in categorys %}
                        <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category }}</a>
                    {% endfor %}
                    <br>
                    <li class="list-group-item list-group-item-dark">Marcas</li>

                    {% for brand in brands %}
                        <a href="{{ brand.get_absolute_url }}" class="list-group-item list-group-item-action">{{ brand }}</a>
                    {% endfor %}
                    <br>

                </div>
            </div>

            <section class="container">
                <div class="row">
                    {% for produto in produtos %}
                        <div class="col-md-3 col-xs-12">
                            <div class="card">
                                <img class="img-responsive card-img-top img-thumbnail" src="/media/{{ produto.image.img }}" alt="{{ produto.image }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ produto }}</h5>
                                    <p class="card-text">Em estoque: {{ produto.stock.quantity }}</p>
                                    <a href="{{ produto.get_absolute_url }}" class="btn btn-primary stretched-link">{{ produto.price.price }} R$</a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </section>
        </div>

    </main>
{% endblock %}